### ISSUE TITLE
*.tmt wiped out after computer crash

### ISSUE THREAD

**Issue by systemovich** [dyadix/TimeCult#11]
My computer froze. I had to do a hard reset. After the computer restarted, I opened TimeCult. A error dialog told me that my *.tmt file had a premature end-of-file. I opened my *.tmt file in a text editor and found the file empty.

How could this happen?

I had Auto-Save switched on. It might have something to do with it.

**Comment by arghtastic** [comment]
I have this problem. . . it's Java related.  This is  a major problem on Linux, which doesn't flush as often as windows.  Please please please improve this.  I've found that it even wipes out previously saved content.
